🚧 🤖📯 Fixtures changed
octokit/fixtures pull request #376
Opened 2020-12-19 04:39 UTC by octokitbot

I found new changes in the recorded fixtures 👋🤖

I can't tell if the changes are fixes, features or breaking, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

2020-12-19 21:20 UTC, gr2m requested changes
I pinged the GitHub API team to verify if this change was intentional or not. I'll wait for them to verify

2020-12-24 06:12 UTC, Mellbabe approved these changes

2021-01-08 08:00 UTC, dominguezcelada commented
> I pinged the GitHub API team to verify if this change was intentional or not. I'll wait for them to verify

@gr2m this has been open since a few days ago. Did you get an answer from Github API team?

2021-01-08 19:21 UTC, gr2m commented
No, but I informed them about it, it's probably not a priority. I'll merge it in for now as it represents the current state of things, which is what we are trying to do with these fixtures

2021-01-08 19:23 UTC, gr2m approved these changes

2021-01-08 19:23 UTC, merged